Add stddef.h to global/types.h (try 2)
While compiling my UNIX port of Tomb1Main, I got some error messages like this one:

In file included from src/game/camera.c:7:
src/game/sound.h:19:5: error: unknown type name ‘size_t’
   19 |     size_t num_samples, const char **sample_pointers, size_t *sizes);
      |     ^~~~~~
src/game/sound.h:1:1: note: ‘size_t’ is defined in header ‘<stddef.h>’; did you forget to '#include <stddef.h>’?
  +++ |+#include <stddef.h>

I would like to suggest to add an #include <stddef.h> into global/types.h.
This fix required some adjustments to satisfy the linters.