build: fix mathlibrary build failure
Since 4de8c65c, build is failing with :
> [...]/x86_64-pc-linux-gnu/bin/ld: TR1X.p/src_game_screen.c.o: undefined reference to symbol 'round@@GLIBC_2.2.5'
> [...]/x86_64-pc-linux-gnu/bin/ld: /lib64/libm.so.6: error adding symbols: DSO missing from command line
> collect2: error: ld returned 1 exit status

math library is missing at linking step.

See also 6610320146f214b37376e302058cb3ba8916e6af

Signed-off-by: Fabrice Delliaux <netbox253@gmail.com>